/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TermsheetIndexRouteImport } from './routes/termsheet/index'
import { Route as DealsIndexRouteImport } from './routes/deals/index'
import { Route as DealsDynamicRouteImport } from './routes/deals/$dynamic'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsheetIndexRoute = TermsheetIndexRouteImport.update({
  id: '/termsheet/',
  path: '/termsheet/',
  getParentRoute: () => rootRouteImport,
} as any)
const DealsIndexRoute = DealsIndexRouteImport.update({
  id: '/deals/',
  path: '/deals/',
  getParentRoute: () => rootRouteImport,
} as any)
const DealsDynamicRoute = DealsDynamicRouteImport.update({
  id: '/deals/$dynamic',
  path: '/deals/$dynamic',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/deals/$dynamic': typeof DealsDynamicRoute
  '/deals': typeof DealsIndexRoute
  '/termsheet': typeof TermsheetIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/deals/$dynamic': typeof DealsDynamicRoute
  '/deals': typeof DealsIndexRoute
  '/termsheet': typeof TermsheetIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/deals/$dynamic': typeof DealsDynamicRoute
  '/deals/': typeof DealsIndexRoute
  '/termsheet/': typeof TermsheetIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/deals/$dynamic' | '/deals' | '/termsheet'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/deals/$dynamic' | '/deals' | '/termsheet'
  id: '__root__' | '/' | '/deals/$dynamic' | '/deals/' | '/termsheet/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DealsDynamicRoute: typeof DealsDynamicRoute
  DealsIndexRoute: typeof DealsIndexRoute
  TermsheetIndexRoute: typeof TermsheetIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/termsheet/': {
      id: '/termsheet/'
      path: '/termsheet'
      fullPath: '/termsheet'
      preLoaderRoute: typeof TermsheetIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deals/': {
      id: '/deals/'
      path: '/deals'
      fullPath: '/deals'
      preLoaderRoute: typeof DealsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deals/$dynamic': {
      id: '/deals/$dynamic'
      path: '/deals/$dynamic'
      fullPath: '/deals/$dynamic'
      preLoaderRoute: typeof DealsDynamicRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DealsDynamicRoute: DealsDynamicRoute,
  DealsIndexRoute: DealsIndexRoute,
  TermsheetIndexRoute: TermsheetIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
